### ISSUE TITLE
uninstall script returns 500 error and renders cluster unusable 

### ISSUE THREAD

**Issue by suhuruli** [Azure/service-fabric-cli#21]
Running the uninstall.sh script generated by Yeoman on a cluster returns an error and renders that cluster unusable until you manually delete the code packages on the nodes. The script will successfully delete and unprovision the application but there will be left over data on the nodes. The error is shown below for when you run the uninstall.sh script:

`Error occurred in request., ConnectionError: HTTPConnectionPool(host='sfpmlinuxignite.eastus.cloudapp.azure.com', port=19080): Max retries exceeded with url: /ImageStore/SimpleContainerApp?api-version=3.0&timeout=60 (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))
Traceback (most recent call last):
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='sfpmlinuxignite.eastus.cloudapp.azure.com', port=19080): Max retries exceeded with url: /ImageStore/SimpleContainerApp?api-version=3.0&timeout=60 (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/msrest/service_client.py", line 189, in send
    **kwargs)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='sfpmlinuxignite.eastus.cloudapp.azure.com', port=19080): Max retries exceeded with url: /ImageStore/SimpleContainerApp?api-version=3.0&timeout=60 (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/azure/servicefabric/service_fabric_client_ap_is.py", line 8141, in delete_image_store_content
    response = self._client.send(request, header_parameters, **operation_config)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/msrest/service_client.py", line 215, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/msrest/exceptions.py", line 47, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/msrest/service_client.py", line 189, in send
    **kwargs)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/servicefabricpm/.local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., ConnectionError: HTTPConnectionPool(host='sfpmlinuxignite.eastus.cloudapp.azure.com', port=19080): Max retries exceeded with url: /ImageStore/SimpleContainerApp?api-version=3.0&timeout=60 (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))`

**Comment by samedder** [comment]
Can you please include logs with the `--debug` flag specified? It's not possible to tell what the response/request is without that.

**Comment by samedder** [comment]
@suhuruli are you still having issues?

**Comment by samedder** [comment]
Close as no repo for now, missing debug logs. Seems to be non-issue.
