### ISSUE TITLE
sfctl application provision --application-type-build-path testPackage fails

### ISSUE THREAD

**Issue by Jose-CF** [Azure/service-fabric-cli#59]
I upload my package with the command `sfctl application upload --path testPackage --show-progress` as usually and this succeeds.

I try to provision my application with: 
`sfctl application provision --application-type-build-path testPackage` and it will fail with this error:

The same operation using Azure CLI 2.x used to work fine.
Since moved to `sfctl` it does not work anymore.

```
Error occurred in request., RetryError: HTTPConnectionPool(host='xx.xx.xx.xx', port=19080): Max retries exceeded with url: /ApplicationTypes/$/Provision?api-version=6.0&timeout=60 (Caused by ResponseError('too many 500 error responses',))
Traceback (most recent call last):
  File "/home/josem/.local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/josem/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/josem/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/josem/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/josem/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 712, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/josem/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='xx.xx.xx.xx', port=19080): Max retries exceeded with url: /ApplicationTypes/$/Provision?api-version=6.0&timeout=60 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/josem/.local/lib/python3.6/site-packages/msrest/service_client.py", line 199, in send
    **kwargs)
  File "/home/josem/.local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/josem/.local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/josem/.local/lib/python3.6/site-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPConnectionPool(host='xx.xx.xx.xx', port=19080): Max retries exceeded with url: /ApplicationTypes/$/Provision?api-version=6.0&timeout=60 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.6/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/xxx/.local/lib/python3.6/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/home/xxx/.local/lib/python3.6/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/home/xxx/.local/lib/python3.6/site-packages/azure/servicefabric/service_fabric_client_ap_is.py", line 2693, in provision_application_type
    request, header_parameters, body_content, **operation_config)
  File "/home/xxx/.local/lib/python3.6/site-packages/msrest/service_client.py", line 225, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/home/xxx/.local/lib/python3.6/site-packages/msrest/exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/home/xxx/.local/lib/python3.6/site-packages/msrest/service_client.py", line 199, in send
    **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/josem/.local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPConnectionPool(host='xx.xx.xx.xx', port=19080): Max retries exceeded with url: /ApplicationTypes/$/Provision?api-version=6.0&timeout=60 (Caused by ResponseError('too many 500 error responses',))
```
Where I put some x's to not to expose sensitive information.

The log in the server says:

```
Info,2746,2589,HttpGateway.HttpGatewayRequestHandler,Invalid URL - http://localhost/ApplicationTypes/$/Provision
```

But that is not the url that I used. I used the url `http://xx.xx.xx.xx:19080/ApplicationTypes/$/Provision`, so that might be indeed the bug.

**Comment by samedder** [comment]
Can you please include the following information:

- `sfctl` version
- Service Fabric cluster runtime version
- Re-run the provision command with the `--debug` flag specified, and capture the debug output

**Comment by Christina-Kang** [comment]
Closing for now. Will re-open if there is new information.
