### ISSUE TITLE
Receiving invalid argument response on most commands

### ISSUE THREAD

**Issue by likewarster** [Azure/service-fabric-cli#66]
- sfctl version: 3.0
- Service Fabric cluster runtime version: 6.1.183.1
- Service Fabric hosting location: Azure
- Local OS: Ubuntu 17.10

When running seemingly any command that interacts with the cluster I am getting an invalid argument response.

sfctl cluster health --debug
```Command arguments: ['cluster', 'health', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fddd693d158>, <function OutputProducer.on_global_arguments at 0x7fddd62198c8>, <function CLIQuery.on_global_arguments at 0x7fddd5fb9510>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x7fddd693d1e0>]
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fddd6219950>, <function CLIQuery.handle_query_parameter at 0x7fddd5fb9598>]
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): 10.1.0.5
urllib3.connectionpool : https://10.1.0.5:19080 "GET /Explorer/$/GetClusterHealth?api-version=6.0&NodesHealthStateFilter=0&ApplicationsHealthStateFilter=0&EventsHealthStateFilter=0&ExcludeHealthStatistics=false&IncludeSystemApplicationHealthStatistics=false&timeout=60 HTTP/1.1" 400 62
msrest.http_logger : Request URL: 'https://10.1.0.5:19080/Explorer/$/GetClusterHealth?api-version=6.0&NodesHealthStateFilter=0&ApplicationsHealthStateFilter=0&EventsHealthStateFilter=0&ExcludeHealthStatistics=false&IncludeSystemApplicationHealthStatistics=false&timeout=60'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'User-Agent': 'python/3.6.3 (Linux-4.13.0-32-generic-x86_64-with-Ubuntu-17.10-artful) requests/2.18.4 msrest/0.4.26 servicefabricclientapis/6.0'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Content-Length': '62'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger : Response content:
msrest.http_logger : b'{"Error":{"Code":"E_INVALIDARG","Message":"Invalid argument"}}'
msrest.exceptions : (E_INVALIDARG) Invalid argument
(E_INVALIDARG) Invalid argument
Traceback (most recent call last):
  File "/home/jordan/.local/lib/python3.6/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/jordan/.local/lib/python3.6/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/home/jordan/.local/lib/python3.6/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/home/jordan/.local/lib/python3.6/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/home/jordan/.local/lib/python3.6/site-packages/azure/servicefabric/service_fabric_client_ap_is.py", line 299, in get_cluster_health
    raise models.FabricErrorException(self._deserialize, response)
azure.servicefabric.models.fabric_error.FabricErrorException: (E_INVALIDARG) Invalid argument
```

**Comment by samedder** [comment]
@likewarster support for 6.1 cluster runtime is coming. Until then this is not a supported case, the latest version of sfctl only supports 6.0 runtime clusters.

**Comment by likewarster** [comment]
@samedder Thank you for the response. Do you happen to know if it is possible to deploy new Service Fabric clusters with older Service Fabric versions on Azure?

**Comment by samedder** [comment]
@likewarster Yes, you should be able to select the cluster version under the `+Optional Features` section when configuring the cluster.

<img width="284" alt="screen shot 2018-02-08 at 12 09 35" src="https://user-images.githubusercontent.com/26749906/35995713-176ff0e6-0cc9-11e8-89c0-ca7224eae8d5.png">

**Comment by samedder** [comment]
@likewarster please update to sfctl 4.0.0, this has support for 6.1 clusters.
