### ISSUE TITLE
sfctl conflicts with recent azure-cli

### ISSUE THREAD

**Issue by wminos** [Azure/service-fabric-cli#72]
## [Info]
- sfctl version: 4.0.0
- azure cli version: 2.0.27
- service fabric hosting location: azure

## [Reason]
two recent cli uses incompatible knack library of different version.
current sfctl cli uses knack@0.1.1
current az cli uses knack@0.3.1

## [Error]
**PS C:\Users\me> pip install sfctl**
**PS C:\Users\me> pip install azure-cli**
**PS C:\Users\me> sfctl**
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\AppData\Roaming\Python\Python36\Scripts\sfctl.exe\__main__.py", line 5, in <module>
  File "C:\Users\me\AppData\Roaming\Python\Python36\site-packages\sfctl\__init__.py", line 16, in <module>
    from sfctl.entry import launch
  File "C:\Users\me\AppData\Roaming\Python\Python36\site-packages\sfctl\entry.py", line 16, in <module>
    from sfctl.commands import SFCommandLoader, SFCommandHelp
  File "C:\Users\me\AppData\Roaming\Python\Python36\site-packages\sfctl\commands.py", line 14, in <module>
    from knack.commands import CLICommandsLoader, CommandSuperGroup
ImportError: cannot import name 'CommandSuperGroup'

## [My solution]
PS> pip check
**sfctl 4.0.0 has requirement knack==0.1.1, but you have knack 0.3.1.**

PS> pip uninstall knack
PS> pip install knack==0.1.1

sfctl okay. 
but azure-cli error occurs.

PS> az
__init__() got multiple values for argument 'ctx'
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\knack\cli.py", line 124, in invoke
    initial_data=initial_invocation_data)
  File "C:\Python36\lib\site-packages\knack\invocation.py", line 31, in __init__
    self.parser = parser_cls(ctx=self.ctx, prog=self.ctx.name, parents=[self._global_parser])
  File "C:\Users\me\AppData\Roaming\Python\Python36\site-packages\azure\cli\core\parser.py", line 39, in __init__
    super(AzCliCommandParser, self).__init__(cli_ctx, cli_help=cli_help, **kwargs)
TypeError: __init__() got multiple values for argument 'ctx'

**Comment by samedder** [comment]
@wminos as a workaround you can run either azure CLI or sfctl from a virtual environment, please take a look at the [virtualenv](https://pypi.python.org/pypi/virtualenv) package.

**Comment by wminos** [comment]
I am using virtualenv. Thank you.

**Comment by samedder** [comment]
@wminos I created an issue from this, #73, to make sure in the future we do upgrade the `knack` package.

**Comment by ryankmcintyre** [comment]
I ran into this and created a container that loads from azure-cli and then installs tmux and uses a virtualenv to load sfctl in a separate environment loaded in a tmux pane. Now my left pane runs az and the right pane runs sfctl. In case someone else finds it useful until the knack version is fixed: [https://hub.docker.com/r/ryanmcintyre/sfctl/](https://hub.docker.com/r/ryanmcintyre/sfctl/)

**Comment by wminos** [comment]
@ryankmcintyre Very cool idea. However, I mainly develop under windows environment and do not use tmux. But it would be useful in a WSL environment.

**Comment by ryankmcintyre** [comment]
It could be run in Docker for Windows after switching it to Linux
containers (doesn't require WSL), but I get your point.
